FROM python:3.13-slim

WORKDIR /backend

COPY pyproject.toml uv.lock ./
RUN pip install --upgrade pip && pip install uv
RUN uv pip install --system --no-cache .

COPY app   ./app
COPY config.py .

EXPOSE 5000

ENV FLASK_APP=app:create_app
ENV FLASK_RUN_PORT=5000
ENV FLASK_RUN_HOST=0.0.0.0

CMD ["flask", "run"]